name: Compile C Code

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile C code
        run: |
          gcc main.c -o main
          ./main
